version: '3.8'

services:
  app:
    restart: always
    build: .
    container_name: a3d-cdn
    ports:
      - "8032:8032"
    volumes:
      - ./library:/app/library
      - ./api-uploads:/app/api-uploads
      - ./uploads:/app/uploads